reject historical place partitioning and print to screen if all are r…
project-lux/data-pipeline pull request #20
Opened 2024-03-15 18:20 UTC by kkdavis14

(if all are rejected)

it's ugly but it should work. any tips on how I can tighten this up? or if there's a better approach entirely. this is what I've come up with. 

rejecting any prop with P582 is easy, it's the printing to screen if they're all rejected that adds all the code.

closes https://git.yale.edu/LUX/pipeline/issues/668

2024-03-15 19:27 UTC, azaroth42 requested changes
Agree it's a bit messy. Especially for just debugging whether we need to care or not.

Proposed an easier solution

2024-03-15 19:27 UTC, azaroth42 commented on pipeline/sources/general/wikidata/fetcher.py
> +        part_ofs = {}
report = False

2024-03-15 19:27 UTC, azaroth42 commented on pipeline/sources/general/wikidata/fetcher.py
> +                        #record it has a prop and a bad qualifier
report = True

2024-03-15 19:27 UTC, azaroth42 commented on pipeline/sources/general/wikidata/fetcher.py
> +                        #record it has a prop and it can go through
report = False

2024-03-15 19:27 UTC, azaroth42 commented on pipeline/sources/general/wikidata/fetcher.py
> +        for k, v in part_ofs.items():
if report:
  print(f"{js['id']} has only parts with ends via P582")

2024-03-15 19:48 UTC, kkdavis14 commented
glad it took me 3 hours to figure out the overly complicated solution (/lays head on desk)

2024-03-15 20:29 UTC, azaroth42 commented
It's learning which tools of the language to use in which situations, and that comes only with time and practice :)

2024-03-15 20:46 UTC, azaroth42 commented
Almost -- needs to deal with the case where there are one or more entries without a qualifier, but the last one has one (which will set to True but shouldn't)

2024-03-18 21:08 UTC, kkdavis14 commented
not convinced this works.

2024-03-27 15:57 UTC, azaroth42 commented on pipeline/sources/general/wikidata/fetcher.py
> +        if all(str(report)) == True:
no need for str() here :)

2024-03-27 16:18 UTC, azaroth42 approved these changes

2024-03-27 16:18 UTC, merged